on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        dockerfile: [3-38, 3-37, 3-38-slim]
    steps:
      - name: PyPi Upload
        env:
          TWINE_USERNAME: ${{ secrets.dockerfile }}
          TWINE_PASSWORD: ${{ secrets.dockerfile }}
        if: matrix.dockerfile == '3-38'
        run: |
          echo "hello"
